# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.CharField(choices=[('SWA', 'Southwest'), ('AAL', 'American'), ('UAL', 'United'), ('DAL', 'Delta'), ('JBU', 'JetBlue')], default='SWA', max_length=3),
        ),
    ]
